/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddUserRoleRequest {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "role")]
    pub role: String,
}

impl AddUserRoleRequest {
    pub fn new(user_id: String, role: String) -> AddUserRoleRequest {
        AddUserRoleRequest {
            user_id,
            role,
        }
    }
}


