/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateNewSessionRequest {
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    /// should be a JSON object (not a JSON literal nor an array)
    #[serde(rename = "userDataInJWT", skip_serializing_if = "Option::is_none")]
    pub user_data_in_jwt: Option<serde_json::Value>,
    /// should be a JSON object (not a JSON literal nor an array)
    #[serde(rename = "userDataInDatabase", skip_serializing_if = "Option::is_none")]
    pub user_data_in_database: Option<serde_json::Value>,
    #[serde(rename = "enableAntiCsrf", skip_serializing_if = "Option::is_none")]
    pub enable_anti_csrf: Option<bool>,
}

impl CreateNewSessionRequest {
    pub fn new() -> CreateNewSessionRequest {
        CreateNewSessionRequest {
            user_id: None,
            user_data_in_jwt: None,
            user_data_in_database: None,
            enable_anti_csrf: None,
        }
    }
}


