/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */

/// CreateJwtAlgorithm : The algorithm to use when creating the JWT.

/// The algorithm to use when creating the JWT.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CreateJwtAlgorithm {
    #[serde(rename = "RS256")]
    Rs256,

}

impl ToString for CreateJwtAlgorithm {
    fn to_string(&self) -> String {
        match self {
            Self::Rs256 => String::from("RS256"),
        }
    }
}

impl Default for CreateJwtAlgorithm {
    fn default() -> CreateJwtAlgorithm {
        Self::Rs256
    }
}




