/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeleteSessionRequest {
    #[serde(rename = "sessionHandles", skip_serializing_if = "Option::is_none")]
    pub session_handles: Option<Vec<String>>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl DeleteSessionRequest {
    pub fn new() -> DeleteSessionRequest {
        DeleteSessionRequest {
            session_handles: None,
            user_id: None,
        }
    }
}


