/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EmailPasswordPutUser200Response {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
}

impl EmailPasswordPutUser200Response {
    pub fn new() -> EmailPasswordPutUser200Response {
        EmailPasswordPutUser200Response {
            status: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "OK")]
    Ok,
    #[serde(rename = "UNKNOWN_USER_ID_ERROR")]
    UnknownUserIdError,
    #[serde(rename = "EMAIL_ALREADY_EXISTS_ERROR")]
    EmailAlreadyExistsError,
}

impl Default for Status {
    fn default() -> Status {
        Self::Ok
    }
}

