/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTelemetry200ResponseOneOf1 {
    #[serde(rename = "exists", skip_serializing_if = "Option::is_none")]
    pub exists: Option<bool>,
}

impl GetTelemetry200ResponseOneOf1 {
    pub fn new() -> GetTelemetry200ResponseOneOf1 {
        GetTelemetry200ResponseOneOf1 {
            exists: None,
        }
    }
}


