/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetUsers200Response {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::StatusOk>,
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<crate::models::GetUsers200ResponseUsersInner>>,
    #[serde(rename = "nextPaginationToken", skip_serializing_if = "Option::is_none")]
    pub next_pagination_token: Option<String>,
}

impl GetUsers200Response {
    pub fn new() -> GetUsers200Response {
        GetUsers200Response {
            status: None,
            users: None,
            next_pagination_token: None,
        }
    }
}


