/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetJwtData200ResponseOneOf {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::StatusOk>,
    /// should be a JSON object (not a JSON literal nor an array)
    #[serde(rename = "userDataInJWT", skip_serializing_if = "Option::is_none")]
    pub user_data_in_jwt: Option<serde_json::Value>,
}

impl GetJwtData200ResponseOneOf {
    pub fn new() -> GetJwtData200ResponseOneOf {
        GetJwtData200ResponseOneOf {
            status: None,
            user_data_in_jwt: None,
        }
    }
}


