/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetUserSessionHandles200Response {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::StatusOk>,
    #[serde(rename = "sessionHandles", skip_serializing_if = "Option::is_none")]
    pub session_handles: Option<Vec<String>>,
}

impl GetUserSessionHandles200Response {
    pub fn new() -> GetUserSessionHandles200Response {
        GetUserSessionHandles200Response {
            status: None,
            session_handles: None,
        }
    }
}


