/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSessionData200Response {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::UnauthorisedResponse>,
    /// should be a JSON object (not a JSON literal nor an array)
    #[serde(rename = "userDataInDatabase", skip_serializing_if = "Option::is_none")]
    pub user_data_in_database: Option<serde_json::Value>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl GetSessionData200Response {
    pub fn new() -> GetSessionData200Response {
        GetSessionData200Response {
            status: None,
            user_data_in_database: None,
            message: None,
        }
    }
}


