/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HelloResponse {
    #[serde(rename = "Hello")]
    Hello,

}

impl ToString for HelloResponse {
    fn to_string(&self) -> String {
        match self {
            Self::Hello => String::from("Hello"),
        }
    }
}

impl Default for HelloResponse {
    fn default() -> HelloResponse {
        Self::Hello
    }
}




