/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InternalError {
    #[serde(rename = "Internal Error")]
    InternalError,

}

impl ToString for InternalError {
    fn to_string(&self) -> String {
        match self {
            Self::InternalError => String::from("Internal Error"),
        }
    }
}

impl Default for InternalError {
    fn default() -> InternalError {
        Self::InternalError
    }
}




