/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NotFound {
    #[serde(rename = "Not Found")]
    NotFound,

}

impl ToString for NotFound {
    fn to_string(&self) -> String {
        match self {
            Self::NotFound => String::from("Not Found"),
        }
    }
}

impl Default for NotFound {
    fn default() -> NotFound {
        Self::NotFound
    }
}




