/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PasswordlessRevokeCodeRequest {
    /// Uniquely identifies a code
    #[serde(rename = "codeId")]
    pub code_id: String,
}

impl PasswordlessRevokeCodeRequest {
    pub fn new(code_id: String) -> PasswordlessRevokeCodeRequest {
        PasswordlessRevokeCodeRequest {
            code_id,
        }
    }
}


