/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PasswordlessListCodes200ResponseDevicesInnerCodesInner {
    /// Uniquely identifies a code
    #[serde(rename = "codeId", skip_serializing_if = "Option::is_none")]
    pub code_id: Option<String>,
    #[serde(rename = "timeCreated", skip_serializing_if = "Option::is_none")]
    pub time_created: Option<f32>,
    /// The maximum lifetime of the code in milliseconds
    #[serde(rename = "codeLifetime", skip_serializing_if = "Option::is_none")]
    pub code_lifetime: Option<f32>,
}

impl PasswordlessListCodes200ResponseDevicesInnerCodesInner {
    pub fn new() -> PasswordlessListCodes200ResponseDevicesInnerCodesInner {
        PasswordlessListCodes200ResponseDevicesInnerCodesInner {
            code_id: None,
            time_created: None,
            code_lifetime: None,
        }
    }
}


