/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PasswordlessListCodes200ResponseDevicesInner {
    /// A random identifier that can be used to identify the login attempt/device.
    #[serde(rename = "preAuthSessionId", skip_serializing_if = "Option::is_none")]
    pub pre_auth_session_id: Option<String>,
    #[serde(rename = "failedCodeInputAttemptCount", skip_serializing_if = "Option::is_none")]
    pub failed_code_input_attempt_count: Option<f32>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    #[serde(rename = "codes", skip_serializing_if = "Option::is_none")]
    pub codes: Option<Vec<crate::models::PasswordlessListCodes200ResponseDevicesInnerCodesInner>>,
}

impl PasswordlessListCodes200ResponseDevicesInner {
    pub fn new() -> PasswordlessListCodes200ResponseDevicesInner {
        PasswordlessListCodes200ResponseDevicesInner {
            pre_auth_session_id: None,
            failed_code_input_attempt_count: None,
            email: None,
            phone_number: None,
            codes: None,
        }
    }
}


