/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PasswordlessStartSignInRequestOneOf2 {
    /// A random identifier that should be stored on the device that started the sign in process.
    #[serde(rename = "deviceId")]
    pub device_id: String,
    /// This can be used to authenticate the user when paired with the deviceId
    #[serde(rename = "userInputCode", skip_serializing_if = "Option::is_none")]
    pub user_input_code: Option<String>,
}

impl PasswordlessStartSignInRequestOneOf2 {
    pub fn new(device_id: String) -> PasswordlessStartSignInRequestOneOf2 {
        PasswordlessStartSignInRequestOneOf2 {
            device_id,
            user_input_code: None,
        }
    }
}


