/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PasswordlessPutUserRequest {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<Box<String>>,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<Box<String>>,
}

impl PasswordlessPutUserRequest {
    pub fn new(user_id: String) -> PasswordlessPutUserRequest {
        PasswordlessPutUserRequest {
            user_id,
            email: None,
            phone_number: None,
        }
    }
}


