/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PasswordlessRevokeAllCodesOfUserRequestOneOf {
    #[serde(rename = "email")]
    pub email: String,
}

impl PasswordlessRevokeAllCodesOfUserRequestOneOf {
    pub fn new(email: String) -> PasswordlessRevokeAllCodesOfUserRequestOneOf {
        PasswordlessRevokeAllCodesOfUserRequestOneOf {
            email,
        }
    }
}


