/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PasswordlessStartSignInRequest {
    #[serde(rename = "email")]
    pub email: String,
    /// This can be used to authenticate the user when paired with the deviceId
    #[serde(rename = "userInputCode", skip_serializing_if = "Option::is_none")]
    pub user_input_code: Option<String>,
    #[serde(rename = "phoneNumber")]
    pub phone_number: String,
    /// A random identifier that should be stored on the device that started the sign in process.
    #[serde(rename = "deviceId")]
    pub device_id: String,
}

impl PasswordlessStartSignInRequest {
    pub fn new(email: String, phone_number: String, device_id: String) -> PasswordlessStartSignInRequest {
        PasswordlessStartSignInRequest {
            email,
            user_input_code: None,
            phone_number,
            device_id,
        }
    }
}


