/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PasswordlessTryUseCode200ResponseOneOf {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::StatusOk>,
    #[serde(rename = "createdNewUser", skip_serializing_if = "Option::is_none")]
    pub created_new_user: Option<bool>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<crate::models::PasswordlessUser>>,
}

impl PasswordlessTryUseCode200ResponseOneOf {
    pub fn new() -> PasswordlessTryUseCode200ResponseOneOf {
        PasswordlessTryUseCode200ResponseOneOf {
            status: None,
            created_new_user: None,
            user: None,
        }
    }
}


