/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PasswordlessTryUseCodeRequestOneOf1 {
    /// A random identifier that can be used to identify the login attempt/device.
    #[serde(rename = "preAuthSessionId", skip_serializing_if = "Option::is_none")]
    pub pre_auth_session_id: Option<String>,
    /// A random identifier that should be stored on the device that started the sign in process.
    #[serde(rename = "deviceId")]
    pub device_id: String,
    /// This can be used to authenticate the user when paired with the deviceId
    #[serde(rename = "userInputCode")]
    pub user_input_code: String,
}

impl PasswordlessTryUseCodeRequestOneOf1 {
    pub fn new(device_id: String, user_input_code: String) -> PasswordlessTryUseCodeRequestOneOf1 {
        PasswordlessTryUseCodeRequestOneOf1 {
            pre_auth_session_id: None,
            device_id,
            user_input_code,
        }
    }
}


