/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PutRole200Response {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::StatusOk>,
    #[serde(rename = "createdNewRole", skip_serializing_if = "Option::is_none")]
    pub created_new_role: Option<bool>,
}

impl PutRole200Response {
    pub fn new() -> PutRole200Response {
        PutRole200Response {
            status: None,
            created_new_role: None,
        }
    }
}


