/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RemoveUserRole200ResponseOneOf {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::StatusOk>,
    #[serde(rename = "didUserHaveRole", skip_serializing_if = "Option::is_none")]
    pub did_user_have_role: Option<bool>,
}

impl RemoveUserRole200ResponseOneOf {
    pub fn new() -> RemoveUserRole200ResponseOneOf {
        RemoveUserRole200ResponseOneOf {
            status: None,
            did_user_have_role: None,
        }
    }
}


