/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ThirdPartySigninupRequest {
    #[serde(rename = "thirdPartyId", skip_serializing_if = "Option::is_none")]
    pub third_party_id: Option<String>,
    #[serde(rename = "thirdPartyUserId", skip_serializing_if = "Option::is_none")]
    pub third_party_user_id: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<Box<crate::models::ThirdPartyEmail>>,
}

impl ThirdPartySigninupRequest {
    pub fn new() -> ThirdPartySigninupRequest {
        ThirdPartySigninupRequest {
            third_party_id: None,
            third_party_user_id: None,
            email: None,
        }
    }
}


