/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TokenTheftResponse {
    #[serde(rename = "TOKEN_THEFT_DETECTED")]
    TokenTheftDetected,

}

impl ToString for TokenTheftResponse {
    fn to_string(&self) -> String {
        match self {
            Self::TokenTheftDetected => String::from("TOKEN_THEFT_DETECTED"),
        }
    }
}

impl Default for TokenTheftResponse {
    fn default() -> TokenTheftResponse {
        Self::TokenTheftDetected
    }
}




