/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserMetadataUpdateRequest {
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    /// should be a JSON object (not a JSON literal nor an array)
    #[serde(rename = "metadataUpdate", skip_serializing_if = "Option::is_none")]
    pub metadata_update: Option<serde_json::Value>,
}

impl UserMetadataUpdateRequest {
    pub fn new() -> UserMetadataUpdateRequest {
        UserMetadataUpdateRequest {
            user_id: None,
            metadata_update: None,
        }
    }
}


