/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserIdMappingUpateExternalUserIdInfoRequest {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "userIdType", skip_serializing_if = "Option::is_none")]
    pub user_id_type: Option<UserIdType>,
    #[serde(rename = "externalUserIdInfo")]
    pub external_user_id_info: Option<String>,
}

impl UserIdMappingUpateExternalUserIdInfoRequest {
    pub fn new(user_id: String, external_user_id_info: Option<String>) -> UserIdMappingUpateExternalUserIdInfoRequest {
        UserIdMappingUpateExternalUserIdInfoRequest {
            user_id,
            user_id_type: None,
            external_user_id_info,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserIdType {
    #[serde(rename = "SUPERTOKENS")]
    Supertokens,
    #[serde(rename = "EXTERNAL")]
    External,
    #[serde(rename = "ANY")]
    Any,
}

impl Default for UserIdType {
    fn default() -> UserIdType {
        Self::Supertokens
    }
}

