/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserIdMappingCreateMapping200Response {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "doesSuperTokensUserIdExist", skip_serializing_if = "Option::is_none")]
    pub does_super_tokens_user_id_exist: Option<bool>,
    #[serde(rename = "doesExternalUserIdExist", skip_serializing_if = "Option::is_none")]
    pub does_external_user_id_exist: Option<bool>,
}

impl UserIdMappingCreateMapping200Response {
    pub fn new() -> UserIdMappingCreateMapping200Response {
        UserIdMappingCreateMapping200Response {
            status: None,
            does_super_tokens_user_id_exist: None,
            does_external_user_id_exist: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "USER_ID_MAPPING_ALREADY_EXISTS_ERROR")]
    UserIdMappingAlreadyExistsError,
}

impl Default for Status {
    fn default() -> Status {
        Self::UserIdMappingAlreadyExistsError
    }
}

