/*
 * Core Driver Interface
 *
 * This is the API exposed by the SuperTokens Core. To be consumed by your backend only.
 *
 * The version of the OpenAPI document: 2.15.1
 * Contact: team@supertokens.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VerifySessionRequest {
    #[serde(rename = "accessToken", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<String>,
    #[serde(rename = "enableAntiCsrf", skip_serializing_if = "Option::is_none")]
    pub enable_anti_csrf: Option<bool>,
    #[serde(rename = "doAntiCsrfCheck", skip_serializing_if = "Option::is_none")]
    pub do_anti_csrf_check: Option<bool>,
    #[serde(rename = "antiCsrfToken", skip_serializing_if = "Option::is_none")]
    pub anti_csrf_token: Option<String>,
}

impl VerifySessionRequest {
    pub fn new() -> VerifySessionRequest {
        VerifySessionRequest {
            access_token: None,
            enable_anti_csrf: None,
            do_anti_csrf_check: None,
            anti_csrf_token: None,
        }
    }
}


